Repository SipheleleNyathi/Online-Shopping-System, pull requests merged in 2022-08, with the labels that each got.

#70 Repository
  src/main/java/za/ac/cput/domain/User.java
  src/main/java/za/ac/cput/domain/UserRole.java
  src/main/java/za/ac/cput/factory/UserFactory.java
  src/main/java/za/ac/cput/factory/UserRoleFactory.java
  src/main/java/za/ac/cput/repository/UserRepository.java
  src/main/java/za/ac/cput/repository/UserRoleRepository.java
Labels: enhancement

#73 Repository classes added and annotated
  onlineShoppingCart.iml
  src/main/java/za/ac/cput/repository/ICategoryRepository.java
  src/main/java/za/ac/cput/repository/IProductRepository.java
Labels: enhancement

#72 Account and Region Repository using JPA framework
  .idea/compiler.xml
  .idea/encodings.xml
  .idea/libraries/Maven__org_apiguardian_apiguardian_api_1_1_2.xml
  .idea/libraries/Maven__org_junit_jupiter_junit_jupiter_api_5_8_2.xml
  .idea/libraries/Maven__org_junit_jupiter_junit_jupiter_engine_5_8_2.xml
  .idea/libraries/Maven__org_junit_platform_junit_platform_commons_1_8_2.xml
  .idea/libraries/Maven__org_junit_platform_junit_platform_engine_1_8_2.xml
  .idea/libraries/Maven__org_opentest4j_opentest4j_1_2_0.xml
  .idea/workspace.xml
  src/main/java/za/ac/cput/domain/Account.java
  src/main/java/za/ac/cput/domain/Region.java
  src/main/java/za/ac/cput/factory/AccountFactory.java
  src/main/java/za/ac/cput/factory/RegionFactory.java
  src/main/java/za/ac/cput/repository/AccountRepository.java
  src/main/java/za/ac/cput/repository/RegionRepository.java
  src/main/java/za/ac/cput/util/GenericHelper.java
  target/classes/za/ac/cput/entity/Account$Builder.class
  target/classes/za/ac/cput/entity/Account.class
  target/classes/za/ac/cput/entity/Payment$Builder.class
  target/classes/za/ac/cput/entity/Region$Builder.class
  target/classes/za/ac/cput/entity/Region.class
  target/classes/za/ac/cput/factory/AccountFactory.class
  target/classes/za/ac/cput/factory/RegionFactory.class
  target/classes/za/ac/cput/factory/UserFactory.class
  target/classes/za/ac/cput/repository/AccountRepository.class
  target/classes/za/ac/cput/repository/IRepository.class
  target/classes/za/ac/cput/repository/RegionRepository.class
  target/classes/za/ac/cput/repository/UserRepository.class
  target/classes/za/ac/cput/util/GenericHelper.class
  target/test-classes/za/ac/cput/entity/AccountTest.class
  target/test-classes/za/ac/cput/entity/RegionTest.class
  target/test-classes/za/ac/cput/factory/AccountFactoryTest.class
  target/test-classes/za/ac/cput/factory/RegionFactoryTest.class
  target/test-classes/za/ac/cput/factory/UserFactoryTest.class
  target/test-classes/za/ac/cput/factory/UserRoleFactoryTest.class
Labels: enhancement

#69 216217717 Repo and Domain
  src/main/java/za/ac/cput/domain/Shipment.java
  src/main/java/za/ac/cput/domain/ShoppingCart.java
  src/main/java/za/ac/cput/repository/ShipmentRepository.java
  src/main/java/za/ac/cput/repository/ShoppingCartRepository.java
Labels: enhancement

#68 217181147
  src/main/java/za/ac/cput/domain/Login.java
  src/main/java/za/ac/cput/domain/Payment.java
  src/main/java/za/ac/cput/repository/LoginRepository.java
  src/main/java/za/ac/cput/repository/PaymentRepository.java
Labels: enhancement

#74 new Pull Request Edvalter_Jamba_220446571_Order_and_OrderDetails_Classess
  src/main/java/za/ac/cput/domain/Order.java
  src/main/java/za/ac/cput/domain/OrderDetails.java
  src/main/java/za/ac/cput/factory/OrderDetailsFactory.java
  src/main/java/za/ac/cput/factory/OrderFactory.java
  src/main/java/za/ac/cput/repository/OrderDetailsRpository.java
  src/main/java/za/ac/cput/repository/OrderRepository.java
  src/test/java/za/ac/cput/factory/OrderDetailsFactoryTest.java
  src/test/java/za/ac/cput/factory/OrderFactoryTest.java
  target/classes/application.yml
  target/classes/za/ac/cput/entity/Account$1.class
  target/classes/za/ac/cput/entity/Category$1.class
  target/classes/za/ac/cput/entity/Category$Builder.class
  target/classes/za/ac/cput/entity/Category.class
  target/classes/za/ac/cput/entity/Login$Builder.class
  target/classes/za/ac/cput/entity/Login.class
  target/classes/za/ac/cput/entity/Order$Builder.class
  target/classes/za/ac/cput/entity/Order.class
  target/classes/za/ac/cput/entity/OrderDetails$Builder.class
  target/classes/za/ac/cput/entity/OrderDetails.class
  target/classes/za/ac/cput/entity/Payment.class
  target/classes/za/ac/cput/entity/Product$1.class
  target/classes/za/ac/cput/entity/Product$Builder.class
  target/classes/za/ac/cput/entity/Product.class
  target/classes/za/ac/cput/entity/Region$1.class
  target/classes/za/ac/cput/entity/Shipment$1.class
  target/classes/za/ac/cput/entity/Shipment$Builder.class
  target/classes/za/ac/cput/entity/Shipment.class
  target/classes/za/ac/cput/entity/ShoppingCart$1.class
  target/classes/za/ac/cput/entity/ShoppingCart$Builder.class
  target/classes/za/ac/cput/entity/ShoppingCart.class
  target/classes/za/ac/cput/entity/User$1.class
  target/classes/za/ac/cput/entity/User$Builder.class
  target/classes/za/ac/cput/entity/User.class
  target/classes/za/ac/cput/entity/UserRole$Builder.class
  target/classes/za/ac/cput/entity/UserRole.class
  target/test-classes/za/ac/cput/repository/AccountRepositoryTest.class
  target/test-classes/za/ac/cput/repository/RegionRepositoryTest.class
Labels: enhancement

#83 SSA - 220041571 (Service Implementation and Test added)
  .idea/compiler.xml
  .idea/workspace.xml
  src/main/java/za/ac/cput/domain/Category.java
  src/main/java/za/ac/cput/service/CategoryService.java
  src/main/java/za/ac/cput/service/IService.java
  src/main/java/za/ac/cput/service/ProductService.java
  src/main/java/za/ac/cput/service/impl/CategoryServiceImpl.java
  src/main/java/za/ac/cput/service/impl/ProductServiceImpl.java
  src/main/java/za/ac/cput/util/GenericHelper.java
  src/test/java/za/ac/cput/service/impl/CategoryServiceImplTest.java
  src/test/java/za/ac/cput/service/impl/ProductServiceImplTest.java
  target/classes/za/ac/cput/entity/Account$Builder.class
  target/classes/za/ac/cput/entity/Account.class
  target/classes/za/ac/cput/entity/Payment$Builder.class
  target/classes/za/ac/cput/entity/Region$Builder.class
  target/classes/za/ac/cput/entity/Region.class
  target/classes/za/ac/cput/factory/AccountFactory.class
  target/classes/za/ac/cput/factory/RegionFactory.class
  target/classes/za/ac/cput/factory/UserFactory.class
  target/classes/za/ac/cput/repository/AccountRepository.class
  target/classes/za/ac/cput/repository/IRepository.class
  target/classes/za/ac/cput/repository/RegionRepository.class
  target/classes/za/ac/cput/repository/UserRepository.class
  target/classes/za/ac/cput/util/GenericHelper.class
  target/test-classes/za/ac/cput/entity/AccountTest.class
  target/test-classes/za/ac/cput/entity/RegionTest.class
  target/test-classes/za/ac/cput/factory/AccountFactoryTest.class
  target/test-classes/za/ac/cput/factory/RegionFactoryTest.class
  target/test-classes/za/ac/cput/factory/UserFactoryTest.class
Labels: documentation, enhancement

#84 Edvalter_Jamba_Order_&_OrderDetails_Services_&_Tests
  .idea/workspace.xml
  src/main/java/za/ac/cput/service/OrderDetailsService.java
  src/main/java/za/ac/cput/service/OrderService.java
  src/main/java/za/ac/cput/service/impl/OrderDetailsServiceImpl.java
  src/main/java/za/ac/cput/service/impl/OrderServiceImpl.java
  src/test/java/za/ac/cput/service/impl/OrderDetailsServiceImplTest.java
  src/test/java/za/ac/cput/service/impl/OrderServiceImplTest.java
Labels: enhancement

#86 217181147
  src/main/java/za/ac/cput/domain/Login.java
  src/main/java/za/ac/cput/factory/LoginFactory.java
  src/main/java/za/ac/cput/factory/PaymentFactory.java
  src/main/java/za/ac/cput/repository/LoginRepository.java
  src/main/java/za/ac/cput/service/LoginService.java
  src/main/java/za/ac/cput/service/PaymentService.java
  src/main/java/za/ac/cput/service/impl/LoginServiceImpl.java
  src/main/java/za/ac/cput/service/impl/PaymentServiceImpl.java
Labels: enhancement

#88 Account and Region Service and Tests
  src/main/java/za/ac/cput/service/AccountService.java
  src/main/java/za/ac/cput/service/RegionService.java
  src/main/java/za/ac/cput/service/impl/AccountServiceImpl.java
  src/main/java/za/ac/cput/service/impl/RegionServiceImpl.java
  src/test/java/za/ac/cput/service/impl/AccountServiceImplTest.java
  src/test/java/za/ac/cput/service/impl/RegionServiceImplTest.java
Labels: enhancement

#89 User & User Role Services with Test cases
  src/main/java/za/ac/cput/service/UserRoleService.java
  src/main/java/za/ac/cput/service/UserService.java
  src/main/java/za/ac/cput/service/impl/UserRoleServiceImpl.java
  src/main/java/za/ac/cput/service/impl/UserServiceImpl.java
  src/test/java/za/ac/cput/service/impl/UserRoleServiceImplTest.java
  src/test/java/za/ac/cput/service/impl/UserServiceImplTest.java
Labels: enhancement

#97 shoppingCart and Shipment Service
  src/main/java/za/ac/cput/service/ShipmentService.java
  src/main/java/za/ac/cput/service/ShoppingCartServise.java
  src/main/java/za/ac/cput/service/impl/ShipmentServiceImpl.java
  src/main/java/za/ac/cput/service/impl/ShoppingCartServiseImpl.java
  src/test/java/za/ac/cput/service/impl/ShipmentServiceImplTest.java
  src/test/java/za/ac/cput/service/impl/ShoppingCartServiseImplTest.java
Labels: enhancement

#98 Changes of the attribute OrderId
  .idea/workspace.xml
  src/main/java/za/ac/cput/domain/Order.java
  src/main/java/za/ac/cput/domain/OrderDetails.java
  src/main/java/za/ac/cput/factory/OrderDetailsFactory.java
  src/test/java/za/ac/cput/factory/OrderDetailsFactoryTest.java
Labels: documentation, enhancement

#99 216217717 Servises
  src/main/java/za/ac/cput/service/ShipmentService.java
  src/main/java/za/ac/cput/service/ShoppingCartServise.java
  src/main/java/za/ac/cput/service/impl/ShipmentServiceImpl.java
  src/main/java/za/ac/cput/service/impl/ShoppingCartServiseImpl.java
  src/test/java/za/ac/cput/service/impl/ShipmentServiceImplTest.java
  src/test/java/za/ac/cput/service/impl/ShoppingCartServiseImplTest.java
Labels: duplicate

#100 Account and Region controller and tests
  src/main/java/za/ac/cput/controller/AccountController.java
  src/main/java/za/ac/cput/controller/RegionController.java
  src/main/java/za/ac/cput/domain/Account.java
  src/main/java/za/ac/cput/service/impl/RegionServiceImpl.java
  src/main/resources/application.properties
  src/test/java/za/ac/cput/controller/AccountControllerTest.java
  src/test/java/za/ac/cput/controller/RegionControllerTest.java
  target/classes/application.properties
Labels: enhancement

#101 Controller and Controller tests added
  .idea/workspace.xml
  src/main/java/za/ac/cput/controller/CategoryController.java
  src/main/java/za/ac/cput/controller/ProductController.java
  src/main/java/za/ac/cput/domain/Category.java
  src/main/java/za/ac/cput/domain/Product.java
  src/main/java/za/ac/cput/factory/ProductFactory.java
  src/test/java/za/ac/cput/controller/CategoryControllerTest.java
  src/test/java/za/ac/cput/controller/ProductControllerTest.java
Labels: enhancement

#104 217181147
  src/main/java/za/ac/cput/controller/LoginController.java
  src/main/java/za/ac/cput/controller/PaymentController.java
  src/test/java/za/ac/cput/controller/LoginControllerTest.java
  src/test/java/za/ac/cput/controller/PaymentControllerTest.java
  src/test/java/za/ac/cput/service/impl/LoginServiceImplTest.java
  src/test/java/za/ac/cput/service/impl/PaymentServiceImplTest.java
Labels: enhancement

#103 220446571_Controller_Order_&OrderDetails_and_tests
  src/main/java/za/ac/cput/controller/OrderController.java
  src/main/java/za/ac/cput/controller/OrderDetailsController.java
  src/test/java/za/ac/cput/controller/OrderControllerTest.java
  src/test/java/za/ac/cput/controller/OrderDetailsControllerTest.java
Labels: enhancement

#105 216217717 Controllers
  src/main/java/za/ac/cput/controller/ShipmentController.java
  src/main/java/za/ac/cput/controller/ShoppingCartController.java
  src/main/java/za/ac/cput/domain/Shipment.java
  src/main/java/za/ac/cput/domain/ShoppingCart.java
  src/main/java/za/ac/cput/factory/ShipmentFactory.java
  src/main/java/za/ac/cput/factory/ShoppingCartFactory.java
  src/test/java/za/ac/cput/controller/ShipmentControllerTest.java
  src/test/java/za/ac/cput/controller/ShoppingCartControllerTest.java
Labels: enhancement
